CREATE TABLE IF NOT EXISTS `returns` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `return_number` VARCHAR(30) NOT NULL,
    `category` ENUM('device','monitor','printer','ram','ssd','charger','accessory','smartboard','phone','ups','graphic','hdd') NOT NULL,
    `item_identifier` VARCHAR(255) NOT NULL,
    `sale_id` INT NULL,
    `sale_item_id` INT NULL,
    `client_name` VARCHAR(100) DEFAULT NULL,
    `client_phone` VARCHAR(20) DEFAULT NULL,
    `description` VARCHAR(255) DEFAULT NULL,
    `quantity` INT NOT NULL DEFAULT 1,
    `unit_price` DECIMAL(10,2) DEFAULT NULL,
    `refund_amount` DECIMAL(10,2) DEFAULT NULL,
    `return_reason` VARCHAR(255) NOT NULL,
    `return_condition` ENUM('Good','Faulty','Damaged','Unknown') NOT NULL DEFAULT 'Unknown',
    `stock_action` ENUM('restock','hold') NOT NULL DEFAULT 'restock',
    `return_status` ENUM('Completed','Cancelled') NOT NULL DEFAULT 'Completed',
    `branch` ENUM('KIMATHI','MOI','WAREHOUSE') DEFAULT NULL,
    `returned_by` INT DEFAULT NULL,
    `returned_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `notes` TEXT DEFAULT NULL,
    `replacement_identifier` VARCHAR(255) DEFAULT NULL,
    `replacement_description` VARCHAR(255) DEFAULT NULL,
    `replacement_price` DECIMAL(10,2) DEFAULT NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uq_returns_return_number` (`return_number`),
    KEY `idx_returns_category_item` (`category`,`item_identifier`),
    KEY `idx_returns_sale_id` (`sale_id`),
    KEY `idx_returns_sale_item_id` (`sale_item_id`),
    KEY `idx_returns_returned_at` (`returned_at`),
    KEY `idx_returns_status` (`return_status`),
    KEY `idx_returns_returned_by` (`returned_by`),
    CONSTRAINT `fk_returns_sale` FOREIGN KEY (`sale_id`) REFERENCES `sales` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_returns_sale_item` FOREIGN KEY (`sale_item_id`) REFERENCES `sale_items` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT `fk_returns_user` FOREIGN KEY (`returned_by`) REFERENCES `users` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
