<?php
session_start();
require_once "../config/db.php";
require_once "../includes/auth_check.php";
require_once "return_helpers.php";
$role=$_SESSION['role']??''; if(!in_array($role,returnsAllowedRoles(),true)) die('Access denied!');
$categories=returnCategories(); $search=trim((string)($_GET['search']??'')); $category=trim((string)($_GET['category']??''));
$allowed=[50,100,150,200]; $per=(int)($_GET['per_page']??50); if(!in_array($per,$allowed,true))$per=50; $page=max(1,(int)($_GET['page']??1));
$where=['1=1'];$params=[];
if($search!==''){ $where[]="(r.return_number LIKE :search OR r.item_identifier LIKE :search OR r.client_name LIKE :search OR r.description LIKE :search)";$params['search']='%'.$search.'%'; }
if($category!==''&&isset($categories[$category])){$where[]='r.category=:category';$params['category']=$category;}
$whereSql=implode(' AND ',$where);
$c=$conn->prepare("SELECT COUNT(*) FROM `returns` r WHERE {$whereSql}");$c->execute($params);$total=(int)$c->fetchColumn();$pages=max(1,(int)ceil($total/$per));if($page>$pages)$page=$pages;$offset=($page-1)*$per;
$stmt=$conn->prepare("SELECT r.*,u.full_name returned_by_name FROM `returns` r LEFT JOIN users u ON u.id=r.returned_by WHERE {$whereSql} ORDER BY r.returned_at DESC,r.id DESC LIMIT :lim OFFSET :off");foreach($params as $k=>$v)$stmt->bindValue(':'.$k,$v);$stmt->bindValue(':lim',$per,PDO::PARAM_INT);$stmt->bindValue(':off',$offset,PDO::PARAM_INT);$stmt->execute();$rows=$stmt->fetchAll(PDO::FETCH_ASSOC);
$stats=$conn->query("SELECT COUNT(*) total_returns,COALESCE(SUM(quantity),0) total_units,COALESCE(SUM(refund_amount),0) total_refunds FROM `returns` WHERE return_status='Completed'")->fetch(PDO::FETCH_ASSOC);
function pageUrl(int $p):string{$q=$_GET;$q['page']=$p;return '?'.http_build_query($q);} function dashboardHref(string $r):string{if($r==='super_admin')return '../dashboard/superadmindashboard';if($r==='manager')return '../dashboard/managerdashboard';return '../dashboard/inventorydashboard';}
?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0,viewport-fit=cover"><title>Returns | Mombasa Computers</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css"><style>
@import url('https://fonts.googleapis.com/css2?family=Inter:opsz,wght@14..32,400;14..32,500;14..32,600;14..32,700&display=swap');:root{--primary:#1a4b2a;--gray-50:#f9fafb;--gray-100:#f3f4f6;--gray-200:#e5e7eb;--gray-300:#d1d5db;--gray-500:#6b7280;--gray-600:#4b5563;--gray-700:#374151;--gray-800:#1f2937;--radius:.5rem;--font:'Inter',system-ui,sans-serif}*{box-sizing:border-box}body{margin:0;font-family:var(--font);background:var(--gray-100);color:var(--gray-800)}.main-content{margin-left:260px;width:calc(100% - 260px);padding:2rem;min-height:100vh}.header,.card,.table-wrap{background:#fff;border:1px solid var(--gray-200);border-radius:1rem}.header{padding:1.5rem 2rem;margin-bottom:1.5rem;display:flex;justify-content:space-between;gap:1rem;align-items:center}.header h1{margin:0;display:flex;gap:.7rem;align-items:center}.header h1 i{color:var(--primary)}.crumb{font-size:.88rem;color:var(--gray-500);margin-top:.45rem}.crumb a{color:var(--primary);text-decoration:none}.btn{padding:.65rem 1rem;border-radius:var(--radius);text-decoration:none;border:0;font-weight:600;display:inline-flex;gap:.5rem;align-items:center}.primary{background:var(--primary);color:#fff}.secondary{background:var(--gray-100);color:var(--gray-700);border:1px solid var(--gray-300)}.stats{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:1rem;margin-bottom:1.5rem}.stat{background:#fff;border:1px solid var(--gray-200);border-radius:.75rem;padding:1.1rem}.value{font-size:1.5rem;font-weight:700}.label{font-size:.8rem;color:var(--gray-500)}.card{padding:1.2rem;margin-bottom:1.5rem}.filters{display:grid;grid-template-columns:2fr 1fr auto;gap:1rem;align-items:end}.field label{display:block;font-size:.8rem;font-weight:600;color:var(--gray-600);margin-bottom:.35rem}.field input,.field select,.pagination select{width:100%;padding:.65rem;border:1px solid var(--gray-300);border-radius:var(--radius);background:#fff}.table-wrap{overflow:hidden}.scroll{overflow-x:auto}table{width:100%;border-collapse:collapse;min-width:1000px}th{background:var(--gray-50);text-align:left;font-size:.8rem;color:var(--gray-600);padding:.9rem}td{padding:.85rem .9rem;border-top:1px solid var(--gray-100);font-size:.87rem}.muted{font-size:.75rem;color:var(--gray-500)}.pagination{padding:1rem;display:flex;justify-content:space-between;gap:1rem;align-items:center;flex-wrap:wrap;border-top:1px solid var(--gray-200)}.pages{display:flex;gap:.35rem}.pages a,.pages span{padding:.4rem .65rem;border:1px solid var(--gray-300);border-radius:var(--radius);text-decoration:none;color:var(--gray-600)}.pages .active{background:var(--primary);color:#fff;border-color:var(--primary)}.empty{text-align:center;padding:2rem;color:var(--gray-500)}@media(max-width:1200px){.main-content{margin-left:0!important;width:100%!important;padding:5rem 1rem 1rem!important}}@media(max-width:800px){.header{flex-direction:column;align-items:stretch}.filters{grid-template-columns:1fr}}
</style></head><body><?php include "../includes/sidebar.php"; ?><div class="main-content"><div class="header"><div><h1><i class="fas fa-rotate-left"></i> Client Returns</h1><div class="crumb"><a href="<?= htmlspecialchars(dashboardHref($role)) ?>"><i class="fas fa-home"></i> Dashboard</a> / Returns</div></div><a class="btn primary" href="create"><i class="fas fa-plus"></i> Record Return</a></div>
<div class="stats"><div class="stat"><div class="value"><?= number_format((int)$stats['total_returns']) ?></div><div class="label">Completed Returns</div></div><div class="stat"><div class="value"><?= number_format((int)$stats['total_units']) ?></div><div class="label">Units Returned</div></div><div class="stat"><div class="value">KES <?= number_format((float)$stats['total_refunds'],2) ?></div><div class="label">Recorded Refunds</div></div></div>
<div class="card"><form method="GET" class="filters"><input type="hidden" name="per_page" value="<?= $per ?>"><div class="field"><label>Search</label><input name="search" value="<?= htmlspecialchars($search) ?>" placeholder="Return no, serial, client or item..."></div><div class="field"><label>Category</label><select name="category"><option value="">All Categories</option><?php foreach($categories as $k=>$cfg): ?><option value="<?= htmlspecialchars($k) ?>" <?= $category===$k?'selected':'' ?>><?= htmlspecialchars($cfg['label']) ?></option><?php endforeach; ?></select></div><div style="display:flex;gap:.5rem"><button class="btn primary"><i class="fas fa-search"></i> Search</button><a class="btn secondary" href="./">Reset</a></div></form></div>
<div class="table-wrap"><div class="scroll"><?php if(!$rows): ?><div class="empty">No returns found.</div><?php else: ?><table><thead><tr><th>#</th><th>Return No.</th><th>Category</th><th>Item</th><th>Client</th><th>Qty</th><th>Condition</th><th>Stock Action</th><th>Branch</th><th>Date</th><th>Action</th></tr></thead><tbody><?php $i=$offset+1;foreach($rows as $r): ?><tr><td><?= $i++ ?></td><td><strong><?= htmlspecialchars($r['return_number']) ?></strong></td><td><?= htmlspecialchars(returnCategoryLabel($r['category'])) ?></td><td><strong><?= htmlspecialchars($r['item_identifier']) ?></strong><div class="muted"><?= htmlspecialchars($r['description']??'') ?></div></td><td><?= htmlspecialchars($r['client_name']??'N/A') ?></td><td><?= (int)$r['quantity'] ?></td><td><?= htmlspecialchars($r['return_condition']) ?></td><td><?= $r['stock_action']==='restock'?'Restocked':'Held' ?></td><td><?= htmlspecialchars($r['branch']??'-') ?></td><td><?= date('M j, Y g:i A',strtotime($r['returned_at'])) ?></td><td><a href="view?id=<?= (int)$r['id'] ?>" style="color:var(--primary);text-decoration:none"><i class="fas fa-eye"></i> View</a></td></tr><?php endforeach; ?></tbody></table><?php endif; ?></div>
<?php if($total>0): ?><div class="pagination"><form method="GET" style="display:flex;gap:.5rem;align-items:center"><?php foreach($_GET as $k=>$v):if($k!=='per_page'&&$k!=='page'&&!is_array($v)): ?><input type="hidden" name="<?= htmlspecialchars($k) ?>" value="<?= htmlspecialchars((string)$v) ?>"><?php endif;endforeach; ?><span>Show</span><select name="per_page" onchange="this.form.submit()"><?php foreach($allowed as $n): ?><option value="<?= $n ?>" <?= $n===$per?'selected':'' ?>><?= $n ?></option><?php endforeach; ?></select><span>per page</span></form><div class="pages"><?php if($page>1): ?><a href="<?= htmlspecialchars(pageUrl($page-1)) ?>">Previous</a><?php endif; ?><?php for($p=max(1,$page-2);$p<=min($pages,$page+2);$p++): ?><?php if($p===$page): ?><span class="active"><?= $p ?></span><?php else: ?><a href="<?= htmlspecialchars(pageUrl($p)) ?>"><?= $p ?></a><?php endif; ?><?php endfor; ?><?php if($page<$pages): ?><a href="<?= htmlspecialchars(pageUrl($page+1)) ?>">Next</a><?php endif; ?></div></div><?php endif; ?></div></div></body></html>
