<?php
session_start();
require_once "../config/db.php";
require_once "../includes/auth_check.php";
$role=$_SESSION['role']??'';$user_id=(int)($_SESSION['user_id']??0);
if(!in_array($role,['super_admin','inventory_admin','manager','technician'],true)) die("Access denied.");
$error='';$success='';
if($_SERVER['REQUEST_METHOD']==='POST'){
$model=trim($_POST['model']??'');$serial=trim($_POST['serial_number']??'');$cargo=trim($_POST['cargo_number']??'');$issue=trim($_POST['issue']??'');$place=trim($_POST['place']??'');$shop=trim($_POST['shop']??'');
if($model==='')$error='Model is required.';elseif($serial==='')$error='Serial number is required.';elseif($shop==='')$error='Shop is required.';else{$dup=$conn->prepare("SELECT 1 FROM faulty_devices WHERE serial_number=:serial AND status='Faulty' LIMIT 1");$dup->execute(['serial'=>$serial]);if($dup->fetchColumn()){$error='This serial number is already listed as Faulty.';}else{$stmt=$conn->prepare("INSERT INTO faulty_devices (model,serial_number,cargo_number,issue,place,shop,status,added_by) VALUES (:model,:serial,:cargo,:issue,:place,:shop,'Faulty',:added_by)");$stmt->execute(['model'=>$model,'serial'=>$serial,'cargo'=>$cargo!==''?$cargo:null,'issue'=>$issue!==''?$issue:null,'place'=>$place!==''?$place:null,'shop'=>$shop,'added_by'=>$user_id]);try{$log=$conn->prepare("INSERT INTO activity_logs (user_id,action,details) VALUES (?,'Faulty Device - Add',?)");$log->execute([$user_id,"Added faulty device $serial ($model)"]);}catch(Throwable $ignored){}$success='Faulty device added successfully.';}}
}
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Add Faulty Device</title><style>body{font-family:Inter,system-ui;background:#f3f4f6;margin:0;color:#1f2937}.main{margin-left:260px;padding:2rem}.card{max-width:760px;margin:auto;background:#fff;border:1px solid #e5e7eb;border-radius:1rem;padding:1.5rem}.grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.field{margin-bottom:1rem}.full{grid-column:1/-1}label{display:block;font-weight:600;font-size:.85rem;margin-bottom:.4rem}input,select,textarea{width:100%;padding:.75rem;border:1px solid #d1d5db;border-radius:.55rem;box-sizing:border-box}.btn{display:inline-flex;padding:.75rem 1rem;border:0;border-radius:.55rem;text-decoration:none;font-weight:600;cursor:pointer}.primary{background:#1a4b2a;color:#fff}.light{background:#e5e7eb;color:#374151}.actions{display:flex;gap:.7rem}.alert{padding:.8rem 1rem;border-radius:.55rem;margin-bottom:1rem}.err{background:#fef2f2;color:#991b1b}.ok{background:#ecfdf5;color:#065f46}@media(max-width:1200px){.main{margin-left:0;padding-top:5rem}}@media(max-width:650px){.grid{grid-template-columns:1fr}.full{grid-column:auto}}</style></head><body><?php include "../includes/sidebar.php"; ?><div class="main"><div class="card"><h2>Add Faulty Device</h2><p>MODEL remains one complete field exactly like the Excel file.</p><?php if($error): ?><div class="alert err"><?= htmlspecialchars($error) ?></div><?php endif; ?><?php if($success): ?><div class="alert ok"><?= htmlspecialchars($success) ?></div><?php endif; ?><form method="POST"><div class="grid"><div class="field full"><label>MODEL</label><textarea name="model" rows="3" required><?= htmlspecialchars($_POST['model']??'') ?></textarea></div><div class="field"><label>SN</label><input name="serial_number" required value="<?= htmlspecialchars($_POST['serial_number']??'') ?>"></div><div class="field"><label>CN</label><input name="cargo_number" value="<?= htmlspecialchars($_POST['cargo_number']??'') ?>"></div><div class="field"><label>ISSUE</label><input name="issue" value="<?= htmlspecialchars($_POST['issue']??'') ?>"></div><div class="field"><label>PLACE</label><input name="place" value="<?= htmlspecialchars($_POST['place']??'') ?>"></div><div class="field"><label>SHOP</label><input name="shop" required value="<?= htmlspecialchars($_POST['shop']??'') ?>" placeholder="Enter shop"></div></div><div class="actions"><button class="btn primary" type="submit">Save Device</button><a class="btn light" href="faulty_devices.php">Back</a></div></form></div></div></body></html>
