<?php
session_start();
require __DIR__ . '/../vendor/autoload.php';
require_once "../config/db.php";
require_once "../includes/auth_check.php";
use PhpOffice\PhpSpreadsheet\IOFactory;
$role=$_SESSION['role']??'';$user_id=(int)($_SESSION['user_id']??0);
if(!in_array($role,['super_admin','inventory_admin','manager','technician'],true)) die("Access denied.");
$success='';$error='';$invalidRows=[];$duplicates=[];
if($_SERVER['REQUEST_METHOD']==='POST'&&isset($_FILES['excel_file'])){
$tmp=$_FILES['excel_file']['tmp_name'];$name=$_FILES['excel_file']['name'];$ext=strtolower(pathinfo($name,PATHINFO_EXTENSION));
if(!in_array($ext,['xlsx','xls','csv'],true)){$error='Upload an Excel or CSV file (.xlsx, .xls, .csv).';}else{try{$rows=IOFactory::load($tmp)->getActiveSheet()->toArray();if(!$rows)throw new Exception('The uploaded file is empty.');$header=array_map(static fn($v)=>strtoupper(trim((string)($v??''))),$rows[0]);$required=['MODEL','SN','CN','ISSUE','PLACE','SHOP'];if(array_slice($header,0,6)!==$required)throw new Exception('Invalid header format. The first 6 columns must be exactly: MODEL, SN, CN, ISSUE, PLACE, SHOP');unset($rows[0]);$added=$duplicateCount=$invalidCount=0;$dup=$conn->prepare("SELECT 1 FROM faulty_devices WHERE serial_number=:serial AND status='Faulty' LIMIT 1");$insert=$conn->prepare("INSERT INTO faulty_devices (model,serial_number,cargo_number,issue,place,shop,status,added_by) VALUES (:model,:serial,:cargo,:issue,:place,:shop,'Faulty',:added_by)");foreach($rows as $index=>$row){$rowNumber=$index+2;$row=array_pad($row,6,'');$model=trim((string)($row[0]??''));$serial=trim((string)($row[1]??''));$cargo=trim((string)($row[2]??''));$issue=trim((string)($row[3]??''));$place=trim((string)($row[4]??''));$shop=trim((string)($row[5]??''));if($model===''&&$serial===''&&$cargo===''&&$issue===''&&$place===''&&$shop==='')continue;$errs=[];if($model==='')$errs[]='MODEL is empty';if($serial==='')$errs[]='SN is empty';if($shop==='')$errs[]='SHOP is empty';if($errs){$invalidCount++;$invalidRows[]="Row $rowNumber: ".implode('; ',$errs);continue;}$dup->execute(['serial'=>$serial]);if($dup->fetchColumn()){$duplicateCount++;$duplicates[]=$serial;continue;}$insert->execute(['model'=>$model,'serial'=>$serial,'cargo'=>$cargo!==''?$cargo:null,'issue'=>$issue!==''?$issue:null,'place'=>$place!==''?$place:null,'shop'=>$shop,'added_by'=>$user_id]);$added++;}try{$log=$conn->prepare("INSERT INTO activity_logs (user_id,action,details) VALUES (?,'Faulty Device - Bulk Upload',?)");$log->execute([$user_id,"Bulk uploaded $added faulty device(s). $duplicateCount duplicate(s), $invalidCount invalid row(s)."]);}catch(Throwable $ignored){}$success="$added faulty device(s) added successfully.";if($duplicateCount)$success.=" $duplicateCount duplicate serial(s) skipped.";if($invalidCount)$success.=" $invalidCount invalid row(s) skipped.";}catch(Throwable $e){$error=$e->getMessage();}}}
?>
<!DOCTYPE html><html><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Bulk Upload Faulty Devices</title><style>body{font-family:Inter,system-ui;background:#f3f4f6;margin:0;color:#1f2937}.main{margin-left:260px;padding:2rem}.card{max-width:900px;margin:auto;background:#fff;border:1px solid #e5e7eb;border-radius:1rem;padding:1.5rem}.format{background:#f9fafb;border:1px solid #e5e7eb;border-radius:.65rem;padding:1rem;margin:1rem 0;font-family:monospace;overflow-x:auto}.btn{display:inline-flex;padding:.75rem 1rem;border:0;border-radius:.55rem;text-decoration:none;font-weight:600;cursor:pointer}.primary{background:#1a4b2a;color:#fff}.light{background:#e5e7eb;color:#374151}.alert{padding:.8rem 1rem;border-radius:.55rem;margin-bottom:1rem}.err{background:#fef2f2;color:#991b1b}.ok{background:#ecfdf5;color:#065f46}.warn{background:#fffbeb;color:#92400e;margin-top:1rem;padding:1rem;border-radius:.55rem}input[type=file]{width:100%;padding:.8rem;border:1px solid #d1d5db;border-radius:.55rem;margin:1rem 0}.actions{display:flex;gap:.7rem;flex-wrap:wrap}@media(max-width:1200px){.main{margin-left:0;padding-top:5rem}}</style></head><body><?php include "../includes/sidebar.php"; ?><div class="main"><div class="card"><h2>Bulk Upload Faulty Devices</h2><p>The upload follows your Excel exactly. <strong>MODEL stays as one complete column</strong>; nothing inside MODEL is split.</p><div class="format">MODEL | SN | CN | ISSUE | PLACE | SHOP</div><p>Example MODEL:</p><div class="format">MICROSOFT SURFACE LAPTOP 3 i7-10TH GEN 16GB 256GB TOUCH</div><?php if($success): ?><div class="alert ok"><?= htmlspecialchars($success) ?></div><?php endif; ?><?php if($error): ?><div class="alert err"><?= htmlspecialchars($error) ?></div><?php endif; ?><?php if($invalidRows): ?><div class="warn"><strong>Invalid Rows</strong><ul><?php foreach($invalidRows as $r): ?><li><?= htmlspecialchars($r) ?></li><?php endforeach; ?></ul></div><?php endif; ?><?php if($duplicates): ?><div class="warn"><strong>Duplicate Faulty Serial Numbers Skipped:</strong> <?= htmlspecialchars(implode(', ',array_unique($duplicates))) ?></div><?php endif; ?><form method="POST" enctype="multipart/form-data"><input type="file" name="excel_file" accept=".xlsx,.xls,.csv" required><div class="actions"><button class="btn primary" type="submit">Upload & Process</button><a class="btn light" href="faulty_devices.php">Back to Faulty Devices</a></div></form></div></div></body></html>
